### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by lunatico67** [gseth/ControlAltAI-Nodes#10]
Hi
Traceback (most recent call last):
  File "C:\Users\luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ControlAltAI-Nodes\__init__.py", line 3, in <module>
    import xformers
ModuleNotFoundError: No module named 'xformers'

 File "C:\Users\luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ControlAltAI-Nodes\__init__.py", line 11, in <module>
    raise ImportError("xformers is required for ControlAltAI Nodes")
ImportError: xformers is required for ControlAltAI Nodes

Cannot import C:\Users\luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ControlAltAI-Nodes module for custom nodes: xformers is required for ControlAltAI Nodes

**Comment by cacerrs** [comment]
Same problem(

**Comment by Djanghost** [comment]
Same here

**Comment by gseth** [comment]
Please check here:

https://github.com/gseth/ControlAltAI-Nodes/issues/9#issuecomment-2525463302

Xformers is required for Attention.

**Comment by gseth** [comment]
Import won't give any errors—update node.

You will get an error only when using Flux Attention Control Node, as it requires XFormers.

![SNAG-4958](https://github.com/user-attachments/assets/20844934-2f0c-4e03-90aa-b5065ca90599)

![SNAG-4959](https://github.com/user-attachments/assets/92038176-9385-46b6-837c-64d744869fa7)

**Comment by gseth** [comment]
> never mind, my bad, I needed to install xformers. Just followed the instructions and now is working properly. Thanks!

The latest update will  import the nodes and only give error on the flux attention node when that specific node is running.

**Comment by lunatico67** [comment]
Hi
gseth, thanks for the help.
I have updated it and it still gives the same error
![Ctrlerror](https://github.com/user-attachments/assets/d28466e0-c319-4dfd-9076-17df30e51cd7)

**Comment by lunatico67** [comment]
Hi
gseth, thanks for the help.
 I have updated it and it still gives the same error
![Ctrlerror--](https://github.com/user-attachments/assets/38159c3d-3c5f-4694-b557-48d2351eb220)

**Comment by lunatico67** [comment]
![Ctrlerror--](https://github.com/user-attachments/assets/da358779-1b47-410a-8b92-eb15454ead82)

Hi
gseth, thanks for the help.
I have updated it and it still gives the same error

**Comment by lunatico67** [comment]
Hi
About xformers I don't have it installed.
I am following the instructions in your text.
I have 2.5.1+cu121
How can i upgrade my cuda to cu124 (for CUDA 12.4) ?

**Comment by gseth** [comment]
> Hi About xformers I don't have it installed. I am following the instructions in your text. I have 2.5.1+cu121 Please, how can i upgrade my cuda to cu124 (for CUDA 12.4) ?

So It was updated two or three times to fix that import issue.

However you can try this command:

python.exe -m pip install xformers==0.0.28.post3 --index-url https://download.pytorch.org/whl/cu121

cu121 men's for Cuda 12.1

**Comment by lunatico67** [comment]
Hi
gseth, thank you for your help.
I have updated the version of cuda and the import failed continues.
 I am in the version of  the portable version of ComfyUI.

**Comment by rachidlamouchi** [comment]
+1

**Comment by gseth** [comment]
> ave updated the version of cuda and the import failed contin

Hi,

I pushes a correct version of update, please update again. Sorry for the regular updates, but the attention node is a bit complicated.

**Comment by gseth** [comment]
> Only this plugin has had a problem since the update, all the others work properly. I'm addicted :/

Please update. The import is fixed.

**Comment by rachidlamouchi** [comment]
Thank you very much, you made us addicted

**Comment by lunatico67** [comment]
Hi
gseth, with this latest update the import failed problem has disappeared. Now it is possible for youtube channel members to use your workflows, thanks for the effort.
