### ISSUE TITLE
Example workflows

### ISSUE THREAD

**Issue by HeavyTony2** [gseth/ControlAltAI-Nodes#11]
Could you provide some example workflows. I'm especially thinking about the "Low Quality" controlnet.

**Comment by gseth** [comment]
An example workflow will not explain how to use low-quality controlnet. A YouTube video explains in-depth details on how to use these tools. Please check this video for low-quality controlnet and other controlnet, including Blur, etc.

https://youtu.be/4_1A5pQkJkg?si=mcRsKwcSpc1uPlDS

**Comment by HeavyTony2** [comment]
I totally disagree, a workflow is quite useful to understand what are the right setting to uses, etc. It's quicker than having to watch a very long video.

**Comment by gseth** [comment]
You may disagree, but the video explains how to build the workflow. We don't share JSON files directly. If you want a JSON file, you can subscribe to be a member on YouTube to get all the JSON files. However, it's recommended to watch the video and build yourself; everything is shown there. Nothing is hidden in the video.

Flux is more complicated than you imagine. Just by giving you a control setting, it will take you hours to figure out how to get the results shown on the GitHub home page. There is a complicated learning curve, but watching a long video is way shorter than you think. We build the node based on how to get the results. We know how much time, research, and testing goes into it.

The workflow for ControlNet is to connect the controlnet union node with a low-quality image as a pre-processor.

**Comment by HeavyTony2** [comment]
I've been experimenting with Flux for a month and I've been using Comfy for nearly a year. I know how I'm able to learn with those tools.

**Comment by gseth** [comment]
Thats good for you. The workflow is quite simple.

Load Flux Diffusion --> Load Image low quality --> directly connect with controlnet union (select it on low quality) --> use conditioning and pass controlnet conditioning to sampler --> output

Some use cases for low quality is:

1. Using a pixelated image to make it into high resolution 3D or just high resolution. Game Assets.
2. You can combine low quality with depth or tile to get character position. (for tile or depth connect the low quality image to tile or depth pre processor and daisy chain that with a second controlnet) Passing conditioning from Controlnet 1 union to Controlnet 2 Union to flux.
