### ISSUE TITLE
Alarm, alarm! Nodes in red after last Comfy update

### ISSUE THREAD

**Issue by Latentnaut** [gseth/ControlAltAI-Nodes#12]
Oh shit I use a lot of ControlAltAI nodes and they all appear in red after last update.

S.O.S.

**Comment by gseth** [comment]
There is no such issue. I just verified on the latest version of Comfy. Post your Start-Up Log.

![image](https://github.com/user-attachments/assets/1d209216-b78c-4c5c-9c42-a5ad01a9a6bd)
![image](https://github.com/user-attachments/assets/ab9fca33-c144-4f55-9cda-812b52fdb01c)

**Comment by gseth** [comment]
@Latentnaut Hi, issue has been fixed. It was not a comfy update. It was the ControlAltAI latest node update. Flux Region Spatial Control Code has been added to the Nodes. The Flux Attention Node requires Xformers for memory attention. The code was checking for xformers and giving error. Now it will only give a warning when using the flux attention node.

**Comment by Latentnaut** [comment]
Awesome! Thank you for your quick action and long life to this fantastic pack!
