### ISSUE TITLE
The Karras option was not found in the scheduler of the flux sampler Node

### ISSUE THREAD

**Issue by boeto** [gseth/ControlAltAI-Nodes#5]
The Karras option was not found in the scheduler of the flux sampler Node. Does this mean Karras is not applicable to flux?  thank you.

**Comment by boeto** [comment]
![Uploading Snipaste_2024-09-06_18-17-35.png…]()

**Comment by gseth** [comment]
Karras doesn’t give desirable results. Only samplers and schedulers which give detailed results are included.
