### ISSUE TITLE
Flux resolution calc comfy ui

### ISSUE THREAD

**Issue by Sterling177** [gseth/ControlAltAI-Nodes#8]
Hey love this Node for Comfy - I compiled a Ratio html viewer - it exported a PNG of your list -  hoping it helps adding a preview onto the node when switching. :) Cant share the html to Git. 
![aspect_ratios](https://github.com/user-attachments/assets/1b99e70c-2014-4675-a83b-4d55ea36ec57)

**Comment by gseth** [comment]
Hi, 

Thanks, but I can add a preview output to the node that generates the ratio preview. The preview file you made I cannot direct use that but generate something similar.

I want to understand the use case for a preview before I decide whether it should be coded in the flux resolution calculator. Does it help to see it visually?

**Comment by gseth** [comment]
> It does help to see the ratio, it’s a really great node ! It would be cool if the node had a preview above like blender texture nodes.. but I’m not sure if that’s possible :) cheers 🥂

Okay so let me see what I can do. I was about to push the regional flux control nodes, Will try and put something for the calculator preview. Will show it here first before finalizing it. Give me some time.

**Comment by gseth** [comment]
> It does help to see the ratio, it’s a really great node ! It would be cool if the node had a preview above like blender texture nodes.. but I’m not sure if that’s possible :) cheers 🥂

Hi How does this look?

![image](https://github.com/user-attachments/assets/7f0de702-105d-4811-828b-d7642755aa36)

![image](https://github.com/user-attachments/assets/66d20d70-4897-451b-adee-12744af833e9)

**Comment by gseth** [comment]
> Looks awesome! Does comfy support this type of config ? If not the preview is very helpful. ![image](https://private-user-images.githubusercontent.com/61482425/392371044-9041a3d5-39bd-4e93-9441-67adaa290ebf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NTg4OTUsIm5iZiI6MTczMzQ1ODU5NSwicGF0aCI6Ii82MTQ4MjQyNS8zOTIzNzEwNDQtOTA0MWEzZDUtMzliZC00ZTkzLTk0NDEtNjdhZGFhMjkwZWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA0MTYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0OWU2Y2EyMDQ5OWVlNjlmZjU1NGYyNjQyMGI0M2Q4YmZmNDFlZDQyYjE2MTQ2ZjM3Y2NkNmJkYWZkOGY0ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fIsi5oCSLH_a7ebrJ3tsej83GV1L3sLHg5fUR-Z5T58)

Great, I will have it pushed in the next update with region control for flux.

The image you posted is a node-based interface, but I don't know which one. It is too low-resolution for me to read anything.

This looks like a 3d Blender output, maybe I am wrong? If it's that, comfy ui doesn't have that. Developing a system like this is comfy. I have to do a feasibility check, and it would be under a paid project (private release only). However, You can find open-source links where Blender is linked to Comfy UI via a bridge.

If its not 3D let me know what it is or upload a higher resolution image please.

**Comment by Sterling177** [comment]
![2024-12-06 19 09 20](https://github.com/user-attachments/assets/cbfd3c94-b0c1-4c6a-8db8-fdfc5d9f0d2a)

Hope this is better. its just blender nodes and the preview is above the node as a selection.. again not sure if comfy is able to do this - your original preview style is super helpful and understand all the time you put in your own :)

**Comment by gseth** [comment]
Flux Resolution Calculator Update is pushed.

@Sterling177 Doing something like this requires a lot of time. It would be a paid project for me.
