### ISSUE TITLE
Error (IMPORT FAILED) after last update (08.12.2004)

### ISSUE THREAD

**Issue by EgorSHep** [gseth/ControlAltAI-Nodes#9]
I received an error (IMPORT FAILED) after the last update.
I even reinstalled ComfyUI and installed only ComfyUI-Manager and ControlAltAI-Nodes ...
below is the data from the console .

F:\ComfyUI_portable>.\python_embeded\python.exe -s ComfyUI\main.py --disable-auto-launch --windows-standalone-build --disable-smart-memory
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-08 08:40:53.816756
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: F:\ComfyUI_portable\python_embeded\python.exe
** ComfyUI Path: F:\ComfyUI_portable\ComfyUI
** Log path: F:\ComfyUI_portable\comfyui.log

Prestartup times for custom nodes:
   2.4 seconds: F:\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16376 MB, total RAM 65415 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce RTX 4080 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: F:\ComfyUI_portable\ComfyUI\web
### ComfyUI Revision: 2890 [9a616b81] *DETACHED | Released on '2024-12-04'
Traceback (most recent call last):
  File "F:\ComfyUI_portable\ComfyUI\nodes.py", line 2037, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\ComfyUI_portable\ComfyUI\custom_nodes\ControlAltAI-Nodes\__init__.py", line 14, in <module>
    from .flux_attention_control_node import FluxAttentionControl
  File "F:\ComfyUI_portable\ComfyUI\custom_nodes\ControlAltAI-Nodes\flux_attention_control_node.py", line 10, in <module>
    from xformers.ops import memory_efficient_attention as xattention
ModuleNotFoundError: No module named 'xformers'

Cannot import F:\ComfyUI_portable\ComfyUI\custom_nodes\ControlAltAI-Nodes module for custom nodes: No module named 'xformers'

Import times for custom nodes:
   0.0 seconds: F:\ComfyUI_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): F:\ComfyUI_portable\ComfyUI\custom_nodes\ControlAltAI-Nodes
   0.2 seconds: F:\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188

**Comment by gseth** [comment]
XFormers is not needed. You can install Xformers without breaking any other dependency by using the following command:

Go to the comfy portable python embedded folder and open CMD.

and run the following command:

`python.exe -m pip install xformers==0.0.28.dev890 --no-dependencies`

After that confirm by 

`python.exe -m pip show xformers`

And it should show you something like:

```
Name: xformers
Version: 0.0.28.dev890
Summary: XFormers: A collection of composable Transformer building blocks.
Home-page: https://facebookresearch.github.io/xformers/
Author: Facebook AI Research
Author-email: oncall+xformers@xmail.facebook.com
License:
Location: Q:\ComfyUI\ComfyUI_2024\python_embeded\Lib\site-packages
Requires: numpy, torch
Required-by:
```

**Comment by EgorSHep** [comment]
Failed to install the xformers package :

RuntimeError:
      The detected CUDA version (11.8) mismatches the version that was used to compile
      PyTorch (12.4). Please make sure to use the same CUDA versions.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for xformers
Failed to build xformers
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (xformers)

F:\ComfyUI_windows_portable\python_embeded>

**Comment by gseth** [comment]
You have to install an older version. Please read instructions again.

**Comment by gseth** [comment]
Import won't give any errors—update node.

You will get an error only when using Flux Attention Control Node, as it requires XFormers.

![SNAG-4958](https://github.com/user-attachments/assets/20844934-2f0c-4e03-90aa-b5065ca90599)

![SNAG-4959](https://github.com/user-attachments/assets/92038176-9385-46b6-837c-64d744869fa7)
